[pytest]
# Добавляем папку src в sys.path, чтобы pytest видел модуль app
pythonpath = src

# Где искать тесты
testpaths = tests

# Флаги по умолчанию при запуске pytest
addopts = -v --tb=short --strict-markers
