server {
  listen 80;
  server_tokens off;

  location / {
    proxy_set_header Host $http_host;
    proxy_pass http://app:8000/;
    client_max_body_size 5M;
  }

  location /media/ {
    alias /media/;
    client_max_body_size 5M;
  }

  location /flower/ {
    auth_basic "Flower Monitoring";
    auth_basic_user_file /etc/nginx/.htpasswd;
    proxy_pass http://flower:5555/flower/;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }
}
