"""make_email_phone_nullable

Revision ID: abc123def456
Revises: 018f44178614
Create Date: 2026-04-15 21:54:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc123def456'
down_revision: Union[str, Sequence[str], None] = '018f44178614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('user', 'phone',
                    existing_type=sa.VARCHAR(length=20),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
                    existing_type=sa.VARCHAR(length=20),
                    nullable=False)
    op.alter_column('user', 'email',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###